Traceback (most recent call last):
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/linares/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import veloxchem as vlx
import gator
import py3Dmol as p3d
import numpy as np
from veloxchem.mointsdriver import MOIntegralsDriver

from matplotlib import pyplot as plt
from matplotlib import colormaps

np.set_printoptions(precision=3, suppress=True)

# Conversion from Hartree to eV for later use
au2ev = vlx.veloxchemlib.hartree_in_ev()

lih_xyz = """2

Li  0.000000   0.000000   0.000000
H   0.000000   0.000000   1.000000
"""

water_xyz = """3

O       0.0000000000     0.0000000000     0.1178336003
H      -0.7595754146    -0.0000000000    -0.4713344012
H       0.7595754146     0.0000000000    -0.4713344012
"""

name = "h2o"


molecule = vlx.Molecule.read_xyz_string(water_xyz)

basis_set_label = "sto-3g"
basis = vlx.MolecularBasis.read(molecule, basis_set_label)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mveloxchem[39;00m [38;5;28;01mas[39;00m [38;5;21;01mvlx[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mgator[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mpy3Dmol[39;00m [38;5;28;01mas[39;00m [38;5;21;01mp3d[39;00m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m

[0;31mModuleNotFoundError[0m: No module named 'gator'
ModuleNotFoundError: No module named 'gator'

