Traceback (most recent call last):
  File "/home/xinli/miniconda3/envs/echem/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/xinli/miniconda3/envs/echem/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/xinli/miniconda3/envs/echem/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/xinli/miniconda3/envs/echem/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/xinli/miniconda3/envs/echem/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/xinli/miniconda3/envs/echem/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/xinli/miniconda3/envs/echem/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Nx = vlx.LinearResponseEigensolver.get_full_solution_vector(lrs_out['solutions'][('x', 0)])
Ny = vlx.LinearResponseEigensolver.get_full_solution_vector(lrs_out['solutions'][('y', 0)])
Nz = vlx.LinearResponseEigensolver.get_full_solution_vector(lrs_out['solutions'][('z', 0)])

print(f"alpha_xx(0): {np.dot(mu_x, Nx) : .6f}")
print(f"alpha_yy(0): {np.dot(mu_y, Ny) : .6f}")
print(f"alpha_zz(0): {np.dot(mu_z, Nz) : .6f}")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[13], line 1[0m
[0;32m----> 1[0m Nx [38;5;241m=[39m [43mvlx[49m[38;5;241;43m.[39;49m[43mLinearResponseEigensolver[49m[38;5;241m.[39mget_full_solution_vector(lrs_out[[38;5;124m'[39m[38;5;124msolutions[39m[38;5;124m'[39m][([38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m, [38;5;241m0[39m)])
[1;32m      2[0m Ny [38;5;241m=[39m vlx[38;5;241m.[39mLinearResponseEigensolver[38;5;241m.[39mget_full_solution_vector(lrs_out[[38;5;124m'[39m[38;5;124msolutions[39m[38;5;124m'[39m][([38;5;124m'[39m[38;5;124my[39m[38;5;124m'[39m, [38;5;241m0[39m)])
[1;32m      3[0m Nz [38;5;241m=[39m vlx[38;5;241m.[39mLinearResponseEigensolver[38;5;241m.[39mget_full_solution_vector(lrs_out[[38;5;124m'[39m[38;5;124msolutions[39m[38;5;124m'[39m][([38;5;124m'[39m[38;5;124mz[39m[38;5;124m'[39m, [38;5;241m0[39m)])

[0;31mAttributeError[0m: module 'veloxchem' has no attribute 'LinearResponseEigensolver'

