Traceback (most recent call last):
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.figure(figsize=(5, 4))
plt.imshow(np.array(E2) - np.array(E2)*np.identity(96))
plt.colorbar()
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[14], line 2[0m
[1;32m      1[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m5[39m, [38;5;241m4[39m))
[0;32m----> 2[0m plt[38;5;241m.[39mimshow(np[38;5;241m.[39marray(E2) [38;5;241m-[39m [43mnp[49m[38;5;241;43m.[39;49m[43marray[49m[43m([49m[43mE2[49m[43m)[49m[38;5;241;43m*[39;49m[43mnp[49m[38;5;241;43m.[39;49m[43midentity[49m[43m([49m[38;5;241;43m96[39;49m[43m)[49m)
[1;32m      3[0m plt[38;5;241m.[39mcolorbar()
[1;32m      4[0m plt[38;5;241m.[39mshow()

[0;31mValueError[0m: operands could not be broadcast together with shapes (288,288) (96,96) 

