Traceback (most recent call last):
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/thomas/miniconda3/envs/echem/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
viewer = mtp.OrbitalViewer()
viewer.plot(molecule, basis, scf_drv.mol_orbs)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[9], line 2[0m
[1;32m      1[0m viewer [38;5;241m=[39m mtp[38;5;241m.[39mOrbitalViewer()
[0;32m----> 2[0m [43mviewer[49m[38;5;241;43m.[39;49m[43mplot[49m[43m([49m[43mmolecule[49m[43m,[49m[43m [49m[43mbasis[49m[43m,[49m[43m [49m[43mscf_drv[49m[38;5;241;43m.[39;49m[43mmol_orbs[49m[43m)[49m

File [0;32m~/miniconda3/envs/echem/lib/python3.11/site-packages/multipsi/OrbitalViewer.py:86[0m, in [0;36mOrbitalViewer.plot[0;34m(self, molecule, basis, mo_object)[0m
[1;32m     82[0m [38;5;28mself[39m[38;5;241m.[39mactive_orbitals [38;5;241m=[39m [38;5;28mlist[39m([38;5;28mself[39m[38;5;241m.[39mspace[38;5;241m.[39mactive_orbitals)
[1;32m     84[0m [38;5;66;03m# Add "active?" widget[39;00m
[1;32m     85[0m [38;5;28mself[39m[38;5;241m.[39misactive [38;5;241m=[39m widgets[38;5;241m.[39mCheckbox(
[0;32m---> 86[0m     value[38;5;241m=[39m([38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mi_orb[49m [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mactive_orbitals), description[38;5;241m=[39m[38;5;124m"[39m[38;5;124mActive[39m[38;5;124m"[39m
[1;32m     87[0m )
[1;32m     88[0m display([38;5;28mself[39m[38;5;241m.[39misactive)
[1;32m     89[0m [38;5;28mself[39m[38;5;241m.[39misactive[38;5;241m.[39mobserve([38;5;28mself[39m[38;5;241m.[39mon_flipactive, names[38;5;241m=[39m[38;5;124m"[39m[38;5;124mvalue[39m[38;5;124m"[39m)

[0;31mAttributeError[0m: 'OrbitalViewer' object has no attribute 'i_orb'

