Traceback (most recent call last):
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/thomas/Notebook/anaconda/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Your code here

# Solution
def harmonic_func(l, l_0, k_s):
    return (k_s / 2.0) * (l - l_0) ** 2

popt, pcov = scipy.optimize.curve_fit(harmonic_func, ref_l, ref_e_shifted)

plt.figure(figsize=(6, 3))
ref_e_shifted = np.array(ref_e) - min(ref_e)
plt.plot(ref_l, ref_e_shifted, "d")
plt.plot(ref_l, harmonic_func(ref_l, *popt))
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[35], line 7[0m
[1;32m      4[0m [38;5;28;01mdef[39;00m [38;5;21mharmonic_func[39m(l, l_0, k_s):
[1;32m      5[0m     [38;5;28;01mreturn[39;00m (k_s [38;5;241m/[39m [38;5;241m2.0[39m) [38;5;241m*[39m (l [38;5;241m-[39m l_0) [38;5;241m*[39m[38;5;241m*[39m [38;5;241m2[39m
[0;32m----> 7[0m popt, pcov [38;5;241m=[39m scipy[38;5;241m.[39moptimize[38;5;241m.[39mcurve_fit(harmonic_func, [43mref_l[49m, ref_e_shifted)
[1;32m      9[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m6[39m, [38;5;241m3[39m))
[1;32m     10[0m ref_e_shifted [38;5;241m=[39m np[38;5;241m.[39marray(ref_e) [38;5;241m-[39m [38;5;28mmin[39m(ref_e)

[0;31mNameError[0m: name 'ref_l' is not defined
NameError: name 'ref_l' is not defined

