Traceback (most recent call last):
  File "/Users/lixin/anaconda3/envs/echem/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/lixin/anaconda3/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/lixin/anaconda3/envs/echem/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/lixin/anaconda3/envs/echem/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/lixin/anaconda3/envs/echem/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/lixin/anaconda3/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/lixin/anaconda3/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/lixin/anaconda3/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Create the Hessian Driver and use it to compute an analytical SCF Hessian
hessian_settings = {'numerical': 'yes', 'do_four_point':'no'}
cphf_settings = {'use_subspace_solver':'yes'}
hessian_drv = vlx.scfhessiandriver.ScfHessianDriver(scfdrv, scfdrv.comm, ostream)
hessian_drv.update_settings(method_settings, hessian_settings, cphf_settings)
hessian_drv.compute(molecule, basis)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [4][0m, in [0;36m<cell line: 4>[0;34m()[0m
[1;32m      2[0m hessian_settings [38;5;241m=[39m {[38;5;124m'[39m[38;5;124mnumerical[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124myes[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mdo_four_point[39m[38;5;124m'[39m:[38;5;124m'[39m[38;5;124mno[39m[38;5;124m'[39m}
[1;32m      3[0m cphf_settings [38;5;241m=[39m {[38;5;124m'[39m[38;5;124muse_subspace_solver[39m[38;5;124m'[39m:[38;5;124m'[39m[38;5;124myes[39m[38;5;124m'[39m}
[0;32m----> 4[0m hessian_drv [38;5;241m=[39m [43mvlx[49m[38;5;241;43m.[39;49m[43mscfhessiandriver[49m[38;5;241m.[39mScfHessianDriver(scfdrv, scfdrv[38;5;241m.[39mcomm, ostream)
[1;32m      5[0m hessian_drv[38;5;241m.[39mupdate_settings(method_settings, hessian_settings, cphf_settings)
[1;32m      6[0m hessian_drv[38;5;241m.[39mcompute(molecule, basis)

[0;31mAttributeError[0m: module 'veloxchem' has no attribute 'scfhessiandriver'
AttributeError: module 'veloxchem' has no attribute 'scfhessiandriver'

