Traceback (most recent call last):
  File "/opt/anaconda3/envs/echem/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/echem/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/envs/echem/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/envs/echem/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/echem/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print(f"<S^2> UDFT  = {singlet_udft_drv.compute_s2(molecule, singlet_u_result):.6}")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[16], line 1[0m
[0;32m----> 1[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124m<S^2> UDFT  = [39m[38;5;132;01m{[39;00m[43msinglet_udft_drv[49m[38;5;241;43m.[39;49m[43mcompute_s2[49m[43m([49m[43mmolecule[49m[43m,[49m[43m [49m[43msinglet_u_result[49m[43m)[49m[38;5;132;01m:[39;00m[38;5;124m.6[39m[38;5;132;01m}[39;00m[38;5;124m"[39m)

File [0;32m/opt/anaconda3/envs/echem/lib/python3.9/site-packages/veloxchem/scfdriver.py:2168[0m, in [0;36mScfDriver.compute_s2[0;34m(self, molecule, scf_tensors)[0m
[1;32m   2165[0m nalpha [38;5;241m=[39m molecule[38;5;241m.[39mnumber_of_alpha_electrons()
[1;32m   2166[0m nbeta [38;5;241m=[39m molecule[38;5;241m.[39mnumber_of_beta_electrons()
[0;32m-> 2168[0m smat [38;5;241m=[39m [43mscf_tensors[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mS[39;49m[38;5;124;43m'[39;49m[43m][49m
[1;32m   2169[0m Cocc_a [38;5;241m=[39m scf_tensors[[38;5;124m'[39m[38;5;124mC_alpha[39m[38;5;124m'[39m][:, :nalpha]
[1;32m   2170[0m Cocc_b [38;5;241m=[39m scf_tensors[[38;5;124m'[39m[38;5;124mC_beta[39m[38;5;124m'[39m][:, :nbeta]

[0;31mTypeError[0m: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable

