Traceback (most recent call last):
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/envs/echem/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/client.py", line 552, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import veloxchem as vlx
import multipsi as mtp
import matplotlib.pyplot as plt
import numpy as np
from scipy import interpolate
from scipy.integrate import simps

mol_str = """
H     0.000000    0.000000   -0.370500
H     0.000000    0.000000    0.370500
"""

au_to_nm = 0.0529177 # length conversion factor
Hz = 0.370500 / 10 / au_to_nm #Position of the H in atomic units.

molecule = vlx.Molecule.read_str(mol_str, units='angstrom')
basis = vlx.MolecularBasis.read(molecule, 'sto-3g')

scf_drv = vlx.ScfRestrictedDriver()
scf_drv.compute(molecule, basis)

space=mtp.MolSpace(molecule,scf_drv.mol_orbs)
space.FCI()
CIdrv=mtp.CIDriver(molecule,basis,space)
CIdrv.compute(1)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/var/folders/yn/sjrk11nj0zs5nb8wzbytm0j00000gn/T/ipykernel_30146/3519695139.py[0m in [0;36m<module>[0;34m[0m
[1;32m     20[0m [0mscf_drv[0m[0;34m.[0m[0mcompute[0m[0;34m([0m[0mmolecule[0m[0;34m,[0m [0mbasis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     21[0m [0;34m[0m[0m
[0;32m---> 22[0;31m [0mspace[0m[0;34m=[0m[0mmtp[0m[0;34m.[0m[0mMolSpace[0m[0;34m([0m[0mmolecule[0m[0;34m,[0m[0mscf_drv[0m[0;34m.[0m[0mmol_orbs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     23[0m [0mspace[0m[0;34m.[0m[0mFCI[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     24[0m [0mCIdrv[0m[0;34m=[0m[0mmtp[0m[0;34m.[0m[0mCIDriver[0m[0;34m([0m[0mmolecule[0m[0;34m,[0m[0mbasis[0m[0;34m,[0m[0mspace[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'multipsi' has no attribute 'MolSpace'
AttributeError: module 'multipsi' has no attribute 'MolSpace'

