Traceback (most recent call last):
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/client.py", line 627, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/util.py", line 89, in ensure_async
    result = await obj
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/envs/echem/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/client.py", line 846, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/client.py", line 651, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/opt/anaconda3/envs/echem/lib/python3.7/site-packages/nbclient/client.py", line 702, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['# Prepare molecule and basis objects', 'molecule = vlx.Molecule.read_str(vinyl_xyz)', 'basis    = vlx.MolecularBasis.read(molecule, "6-31G")', '', '# SCF settings and calculation']
...
["    axx = -cpp_prop.rsp_property['response_functions'][('x', 'x', w)].imag", "    ayy = -cpp_prop.rsp_property['response_functions'][('y', 'y', w)].imag", "    azz = -cpp_prop.rsp_property['response_functions'][('z', 'z', w)].imag", '    alpha_bar = (axx + ayy + azz) / 3.0', '    sigma.append(4.0 * np.pi * w * alpha_bar / 137.035999)']
-------------------

